name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.5
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  csv: ^5.0.2
  lottie: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flags/